site_name: Lambda Docs
theme:
  name: material
  features:
    - navigation.tabs
      #    - toc.integrate
  palette:
    primary: deep purple
  logo: assets/img/lambda-logo.jpg
nav:
  - Home: index.md
  - On-Demand Cloud:
    - on-demand-cloud/getting-started.md
    - on-demand-cloud/billing.md
  - 1-Click Clusters:
    - 1-click-clusters/getting-started.md
  - Workstations:
    - workstations/getting-started.md
  - Software:
    - software/virtual-environments-containers.md
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - sane_lists
  - tables
  - toc:
      permalink: "#"
plugins:
  - git-revision-date-localize
  - search
  - redirects:
      redirect_maps:
        'one-click-clusters/getting-started.md': '1-click-clusters/getting-started.md'
  - tags:
      tags_file: tags.md
