site_name: Lambda Docs [PROOF OF CONCEPT]
site_url: https://cbrownstein-lambda.github.io/lambda-docs-mkdocs/
repo_url: https://github.com/cbrownstein-lambda/lambda-docs-mkdocs
edit_uri: edit/main/docs/
theme:
  name: material
  features:
    - navigation.tabs
    - content.action.view
    - content.action.edit
    - content.code.copy
      #    - toc.integrate
  palette:
    primary: deep purple
  logo: assets/img/lambda-logo.png
  favicon: assets/img/lambda-logo.png
  custom_dir: overrides
nav:
  - Home: index.md
  - On-Demand Cloud:
    - on-demand-cloud/getting-started.md
    - on-demand-cloud/billing.md
  - 1-Click Clusters:
    - 1-click-clusters/getting-started.md
  - Workstations:
    - workstations/getting-started.md
  - Software:
    - software/virtual-environments-containers.md
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - sane_lists
  - tables
  - toc:
      permalink: "#"
plugins:
  - git-committers:
      repository: cbrownstein-lambda/lambda-docs-mkdocs
      branch: main
  - git-revision-date-localized
  - include-markdown
  - search
  - social
  - redirects:
      redirect_maps:
        'one-click-clusters/getting-started.md': '1-click-clusters/getting-started.md'
  - tags:
      tags_file: tags.md
extra:
  social:
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/LambdaAPI
