site_description: Lambda GPU Cloud documentation
site_name: Lambda Docs [PROOF OF CONCEPT]
site_url: https://cbrownstein-lambda.github.io/lambda-docs-mkdocs/
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - navigation.expand
    - content.code.copy
      #    - toc.integrate
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: custom
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: custom
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  logo: assets/images/lambda/lambda_docs_logo.svg
  favicon: assets/images/lambda/lambda-logo.png
  custom_dir: overrides
nav:
  - Home: index.md
  - Public Cloud:
    - public-cloud/index.md
    - On-Demand:
      - public-cloud/on-demand/index.md
      - public-cloud/on-demand/getting-started.md
      - public-cloud/on-demand/dashboard.md
      - public-cloud/on-demand/billing.md
      - public-cloud/on-demand/guest-agent.md
    - 1-Click Clusters:
      - public-cloud/1-click-clusters/getting-started.md
      - public-cloud/1-click-clusters/serving-llama-3_1-405b.md
      - public-cloud/1-click-clusters/security-posture.md
    - public-cloud/filesystems.md
    - public-cloud/firewalls.md
    - public-cloud/teams.md
    - public-cloud/cloud-api.md
  - Private Cloud:
      - private-cloud/index.md
  - Hardware:
      - hardware/index.md
      - Servers:
        - Unboxing and Setup:
          - hardware/servers/unboxing-and-setup/power-and-network-cables.md
          - hardware/servers/unboxing-and-setup/using-bmc-ipmi.md
      - Workstations:
          - hardware/workstations/getting-started.md
          - hardware/workstations/troubleshooting.md
  - Education:
    - education/index.md
    - Generative AI:
      - education/generative-ai/flux-prompt-to-image.md
    - Large language models (LLMs):
      - education/large-language-models/serving-llama-3-1-docker.md
      - education/large-language-models/lambda-chat-api.md
    - Programming:
      - education/programming/vs-code-lambda-chat.md
    - Scheduling and orchestration:
      - education/scheduling-and-orchestration/dstack-vllm-llama-3-1.md
      - education/scheduling-and-orchestration/installing-k3s.md
      - education/scheduling-and-orchestration/ray-cluster-kubernetes.md
      - education/scheduling-and-orchestration/skypilot-deploy-kubernetes.md
    - Basic Linux usage and system administration:
      - education/linux-usage/virtual-environments-containers.md
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: vegalite
          class: vegalite
          format: !!python/name:mkdocs_charts_plugin.fences.fence_vegalite
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - sane_lists
  - tables
  - toc:
      permalink: "#"
plugins:
  - charts
  - glightbox
  - include-markdown
  - search
  - social
  - redirects:
      redirect_maps:
        'one-click-clusters/getting-started.md': 'public-cloud/1-click-clusters/getting-started.md'
        'on-demand-cloud/getting-started.md': 'public-cloud/on-demand/getting-started.md'
  - tags:
      tags_file: tags.md
extra_css:
  - assets/css/extra.css
  - assets/css/glightbox.min.css
extra_javascript:
  - assets/js/glightbox.min.js
  - assets/js/docs-landing-page.js
  - https://cdn.jsdelivr.net/npm/vega@5
  - https://cdn.jsdelivr.net/npm/vega-lite@5
  - https://cdn.jsdelivr.net/npm/vega-embed@6
  - https://js.hs-scripts.com/21998649.js
extra:
  social:
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/LambdaAPI
  analytics:
    provider: google
    property: G-43EZT1FM6Q
