site_name: Lambda Docs [PROOF OF CONCEPT]
site_url: https://cbrownstein-lambda.github.io/lambda-docs-mkdocs/
repo_url: https://github.com/cbrownstein-lambda/lambda-docs-mkdocs
edit_uri: edit/main/docs/
theme:
  name: material
  features:
    - navigation.tabs
    - content.action.view
    - content.action.edit
    - content.code.copy
      #    - toc.integrate
  palette:
    primary: deep purple
  logo: assets/img/lambda-logo.png
  favicon: assets/img/lambda-logo.png
  custom_dir: overrides
nav:
  - Home: index.md
  - On-Demand Cloud:
    - on-demand-cloud/getting-started.md
    - on-demand-cloud/billing.md
    - on-demand-cloud/serving-llama-3-1-docker.md
    - on-demand-cloud/flux-prompt-to-image.md
    - on-demand-cloud/lambda-chat-api.md
  - 1-Click Clusters:
    - 1-click-clusters/getting-started.md
    - 1-click-clusters/serving-llama-3_1-405b.md
  - Workstations:
    - workstations/getting-started.md
    - workstations/troubleshooting.md
  - Guides:
      - guides/index.md
      - Large language models (LLMs):
        - guides/large-language-models/lambda-chat-api.md
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: vegalite
          class: vegalite
          format: !!python/name:mkdocs_charts_plugin.fences.fence_vegalite
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - sane_lists
  - tables
  - toc:
      permalink: "#"
plugins:
  - charts
  - git-committers:
      repository: cbrownstein-lambda/lambda-docs-mkdocs
      branch: main
  - git-revision-date-localized
  - include-markdown
  - search
  - social
  - redirects:
      redirect_maps:
        'one-click-clusters/getting-started.md': '1-click-clusters/getting-started.md'
  - tags:
      tags_file: tags.md
extra_javascript:
  - https://cdn.jsdelivr.net/npm/vega@5
  - https://cdn.jsdelivr.net/npm/vega-lite@5
  - https://cdn.jsdelivr.net/npm/vega-embed@6
extra:
  social:
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/LambdaAPI
