site_name: Lambda Docs [PROOF OF CONCEPT]
site_url: https://cbrownstein-lambda.github.io/lambda-docs-mkdocs/
repo_url: https://github.com/cbrownstein-lambda/lambda-docs-mkdocs
edit_uri: edit/main/docs/
theme:
  name: material
  features:
    - navigation.tabs
    - content.action.view
    - content.action.edit
    - content.code.copy
      #    - toc.integrate
  palette:
    primary: deep purple
    scheme: slate
  logo: assets/img/lambda-logo.png
  favicon: assets/img/lambda-logo.png
  custom_dir: overrides
nav:
  - Home: index.md
  - Public Cloud:
    - public-cloud/index.md
    - On-Demand:
      - public-cloud/on-demand/getting-started.md
      - public-cloud/on-demand/billing.md
      - public-cloud/on-demand/flux-prompt-to-image.md
    - 1-Click Clusters:
      - public-cloud/1-click-clusters/getting-started.md
      - public-cloud/1-click-clusters/serving-llama-3_1-405b.md
  - Private Cloud:
      - private-cloud/index.md
  - Hardware:
      - hardware/index.md
      - Servers:
        - Unboxing and Setup:
          - hardware/servers/unboxing-and-setup/power-and-network-cables.md
          - hardware/servers/unboxing-and-setup/using-bmc-ipmi.md
      - Workstations:
          - hardware/workstations/getting-started.md
          - hardware/workstations/troubleshooting.md
  - Education:
    - education/index.md
    - Generative AI:
      - education/generative-ai/flux-prompt-to-image.md
    - Large language models (LLMs):
      - education/large-language-models/serving-llama-3-1-docker.md
      - education/large-language-models/lambda-chat-api.md
    - Kubernetes (K8s):
      - education/kubernetes/installing-k3s.md
      - education/kubernetes/ray-cluster-kubernetes.md
    - Basic Linux usage and system administration:
      - education/linux-usage/virtual-environments-containers.md
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: vegalite
          class: vegalite
          format: !!python/name:mkdocs_charts_plugin.fences.fence_vegalite
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - sane_lists
  - tables
  - toc:
      permalink: "#"
plugins:
  - charts
  - git-committers:
      repository: cbrownstein-lambda/lambda-docs-mkdocs
      branch: main
  - git-revision-date-localized
  - include-markdown
  - search
  - social
  - redirects:
      redirect_maps:
        'one-click-clusters/getting-started.md': '1-click-clusters/getting-started.md'
  - tags:
      tags_file: tags.md
extra_javascript:
  - https://cdn.jsdelivr.net/npm/vega@5
  - https://cdn.jsdelivr.net/npm/vega-lite@5
  - https://cdn.jsdelivr.net/npm/vega-embed@6
extra:
  social:
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/LambdaAPI
