name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-22.04
    steps:
      - name: Check out main
        uses: actions/checkout@v4.1.6

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@v1.26
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
